version: '2'

services:  
  front:
    image: nginx
    ports:
      - 80
    volumes:
      - .:/home/docker:ro
      - ./docker/front/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - default
  
  engine:
    build: ./docker/engine/
    volumes:
      - .:/home/docker:rw
      - ./docker/engine/php.ini:/usr/local/etc/php/conf.d/custom.ini:ro
    working_dir: /home/docker
    networks:
      - default
    dns_search:
      - engine

  elk:
    image: willdurand/elk
    ports:
      - 80
    volumes:
      - ./elk/logstash:/etc/logstash
      - ./elk/logstash/patterns:/opt/logstash/patterns
    volumes_from:
      - php
      - nginx
   networks:
      - default
    dns_search:
      - engine



volumes:
  db: {}
networks:
  default: {}