export { CategoryService } from './service/category.service';
export { CategoryItemComponent } from './item/category-item.component';
export { CategoryDetailComponent } from './detail/category-detail.component';
export { CategoryListComponent } from './list/category-list.component';
export { CategoryLastComponent } from './list/category-last.component';
export { CategoryDescoveryComponent } from './list/category-descovery.component';
export { CategorySuggestionComponent } from './list/category-suggestion.component';
export { CategoryMenuComponent } from './list/category-menu.component';
export { CategoryFollowComponent } from './list/category-follow.component';
