FROM php:7-fpm
MAINTAINER LITHOS CRISTAL <cristallithos@gmail.com>

ARG NODEJS_VERSION = 4.2.6

RUN apt-get update \
    && apt-get install -y \
        git \
        unzip\
        nmon\
        htop\
        landscape-common\
        multitail\
        apachetop\
